[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "numerica"
version = "0.1.0"
description = "Numerical methods toolkit for applied mathematics"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

authors = [
    { name = "Hada" }
]

dependencies = [
    "numpy>=2.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
    "build"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 88

[tool.mypy]
python_version = "3.10"
strict = true